### ISSUE TITLE
Remove ".env" File from Project

### ISSUE THREAD

**Issue by mohsen12999** [MotahareFallah/issue_tracker#2]
### Summary

The `.env` file is currently tracked in the repository, which poses a risk of exposing sensitive information such as API keys, database credentials, and other environment-specific configurations.

### Proposal

I propose that we remove the `.env` file from the project and add it to our `.gitignore` file to prevent it from being tracked in the future. This will help ensure that sensitive information is not inadvertently shared in our version control system.

### Action Items

1. Remove the `.env` file from the repository.
2. Add `.env` to the `.gitignore` file.
3. Ensure that any necessary environment variables are documented for local development.

### Additional Notes

If there are any environment variables currently stored in the `.env` file, we should ensure they are securely communicated to team members who need them for development purposes.

Thank you!

**Comment by MotahareFallah** [comment]
Thank you. These are not sensitive data. I am just showcasing my abilities.

**Comment by mohsen12999** [comment]
but we need to add a section in project guide to make `.env` file
